<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Configurations>Debug;Release;DebugWithDisableAzure</Configurations>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <PackageIcon>Icon.png</PackageIcon>
	  <NoWarn>$(NoWarn);WPF0001</NoWarn>
	  <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugWithDisableAzure|AnyCPU'">
    <DefineConstants>$(DefineConstants);DISABLEAZURE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icon.png" />
    <None Remove="Splash.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" />
    <EmbeddedResource Include="Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <OpenApiReference Include="OpenAPIs\swagger.json" Namespace="Ma.TimeManagement.OpenAPIService" Options="/GenerateDtoTypes:false /AdditionalNamespaceUsages:Ma.TimeManagement.Models" ClassName="MaTimeManagmentApiClient">
      <SourceUri>https://localhost:7185/swagger/v1/swagger.json</SourceUri>
    </OpenApiReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="7.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NSwag.ApiDescription.Client" Version="13.18.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <!--<PackageReference Include="System.Net.Http" Version="4.3.4" />-->
    <!--<PackageReference Include="WPF-UI" Version="4.0.3" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ma.TimeManagement.Migrations.Sqlite\Ma.TimeManagement.Migrations.Sqlite.csproj" />
    <ProjectReference Include="..\Ma.TimeManagement.Share\Ma.TimeManagement.Share.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="Splash.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
