// <auto-generated />
using System;
using Ma.TimeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ma.TimeManagement.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ma.TimeManagement.Models.TeamProjectReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTeamImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequiredPermissions")
                        .HasColumnType("int");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TeamProjects");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdoPatEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdoPatIv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkCalendarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DurationHour")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Synced")
                        .HasColumnType("bit");

                    b.Property<int?>("WorkItemID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemID");

                    b.ToTable("WorkCalendarItems");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("CompletedWork")
                        .HasColumnType("float");

                    b.Property<double>("OriginalEstimate")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RemainingWork")
                        .HasColumnType("float");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkItemType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectID");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkCalendarItem", b =>
                {
                    b.HasOne("Ma.TimeManagement.Models.WorkItem", "WorkItem")
                        .WithMany("WorkCalendarItems")
                        .HasForeignKey("WorkItemID");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkItem", b =>
                {
                    b.HasOne("Ma.TimeManagement.Models.TeamProjectReference", "ProjectReference")
                        .WithMany("workItems")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectReference");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.TeamProjectReference", b =>
                {
                    b.Navigation("workItems");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkItem", b =>
                {
                    b.Navigation("WorkCalendarItems");
                });
#pragma warning restore 612, 618
        }
    }
}
