// <auto-generated />
using System;
using Ma.TimeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ma.TimeManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119115834_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Ma.TimeManagement.Models.TeamProjectReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTeamImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredPermissions")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TeamProjects");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkCalendarItem", b =>
                {
                    b.Property<DateTime>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkItemID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemID");

                    b.ToTable("WorkCalendarItems");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CompletedWork")
                        .HasColumnType("REAL");

                    b.Property<double>("OriginalEstimate")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RemainingWork")
                        .HasColumnType("REAL");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkItemType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectReferenceId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkCalendarItem", b =>
                {
                    b.HasOne("Ma.TimeManagement.Models.WorkItem", "WorkItem")
                        .WithMany("WorkCalendarItems")
                        .HasForeignKey("WorkItemID");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkItem", b =>
                {
                    b.HasOne("Ma.TimeManagement.Models.TeamProjectReference", "ProjectReference")
                        .WithMany("workItems")
                        .HasForeignKey("ProjectReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectReference");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.TeamProjectReference", b =>
                {
                    b.Navigation("workItems");
                });

            modelBuilder.Entity("Ma.TimeManagement.Models.WorkItem", b =>
                {
                    b.Navigation("WorkCalendarItems");
                });
#pragma warning restore 612, 618
        }
    }
}
